Todo branch
admirerbrown/todo-react-app pull request #2
Opened 2023-01-17 09:39 UTC by admirerbrown

**this branch has the following functionality.**

- the setup of the project
- adds adding todos functionality to the app
- adds editing todos functionality to the app
- adds deleting todos functionality to the app
- adds checking todos functionality to the app
- adds marking todos as completed to the app
- add professional descriptive readme file

2023-01-17 12:00 UTC, IndieCoderMM requested changes
# Status: Required Changes 🟡
Hi @admirerbrown , 
Great job on building a fully working to-do app using React! 👍
I think there are some modifications you can make to improve the code quality. ✨

## Highlights 🥇
- Used correct git flow ✔
- Descriptive PR ✔
- Descriptive README ✔
- All features work perfectly ✔
- Great use of React components ✔
- Clean and organize code ✔

## Suggestion 📌
I have one suggestion to help you improve your code quality. You can add `type="button"` attribute to `<button>` tags to fix ESLint button-type errors.
Kindly check the comment below for more details. 

Keep up the good work! 💪

**Happy coding!** 😎

*If something is not 100% clear, feel free to ask questions in the comment.*

2023-01-17 12:00 UTC, IndieCoderMM commented on src/components/TodoItem.js
> +          <button type="" onClick={() => this.props.deleteTodoProps(id)}>
You can add `type="button"`  attribute here to fix ESLint button-type error. I think it will improve your overall code quality. 😉

2023-01-17 18:41 UTC, admirerbrown commented on src/components/TodoItem.js
> +          <button type="" onClick={() => this.props.deleteTodoProps(id)}>
Thank you for the great review.

2023-01-18 04:25 UTC, IndieCoderMM approved these changes
# Status: Approved 🟢
Hi @admirerbrown , 
Thanks for implementing the requested changes. 😀
Your project is complete. It's time to merge it. 🎉🎉🎊
<img src="https://media2.giphy.com/media/l41YmQjOz9qg2Ecow/giphy.gif"/>

## Highlights 🎖
- No linter errors ✔
- Correct Git flow ✔
- All app features work perfectly ✔

*Thanks for your hard work.*
**Happy Coding!** 😎

2023-01-18 07:36 UTC, merged